server:
  port: 8882

spring:
  application:
    name: rainbow-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 101.132.105.134:8848

    gateway:
      routes:
        - id: rainbow-auth
          uri: lb://rainbow-auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: auth-fallback
                fallbackUri: forward:/fallback/rainbow-auth
        - id: rainbow-system-server
          uri: lb://rainbow-system-server
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: system-fallback
                fallbackUri: forward:/fallback/rainbow-system-server
        - id: rainbow-bus
          uri: lb://rainbow-bus
          predicates:
            - Path=/bus/**
          filters:
            - name: Hystrix
              args:
                name: bus-fallback
                fallbackUri: forward:/fallback/rainbow-bus
      default-filters:
        - StripPrefix=1