server:
  port: 8886


spring:
  application:
    name: rainbow-search

  #注册nacos
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.105.134:8848

  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: my-cluster

# 为了让feign获得token
hystrix:
  shareSecurityContext: true

# 客户端的每一次请求都会去认证服务器校验token
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8882/auth/user


##自定义配置
rainbow:
  cloud:
    security:
#      # 免认证url 多个逗号拼接
#      anonUris: /captcha,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/email/**
#      # 是否禁止请求绕过网关
      enable: true