server:
  port: 8882

spring:
  application:
    name: rainbow-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 101.132.105.134:8848

    gateway:
      routes:
        - id: rainbow-auth
          uri: lb://rainbow-auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: auth-fallback
                fallbackUri: forward:/fallback/rainbow-auth
        - id: rainbow-system-server
          uri: lb://rainbow-system-server
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: system-fallback
                fallbackUri: forward:/fallback/rainbow-system-server
        - id: rainbow-bus
          uri: lb://rainbow-bus
          predicates:
            - Path=/bus/**
          filters:
            - name: Hystrix
              args:
                name: bus-fallback
                fallbackUri: forward:/fallback/rainbow-bus
        - id: rainbow-upload
          uri: lb://rainbow-upload
          predicates:
            - Path=/upload/**
          filters:
            - name: Hystrix
              args:
                name: rainbow-upload
                fallbackUri: forward:/fallback/rainbow-upload
        - id: rainbow-search
          uri: lb://rainbow-search
          predicates:
            - Path=/search/**
          filters:
            - name: Hystrix
              args:
                name: rainbow-search
                fallbackUri: forward:/fallback/rainbow-search
        - id: rainbow-generator
          uri: lb://rainbow-generator
          predicates:
            - Path=/search/**
          filters:
            - name: Hystrix
              args:
                name: rainbow-generator
                fallbackUri: forward:/fallback/rainbow-generator
        - id: rainbow-job
          uri: lb://rainbow-job
          predicates:
            - Path=/job/**
          filters:
            - name: Hystrix
              args:
                name: rainbow-job
                fallbackUri: forward:/fallback/rainbow-job
      default-filters:
        - StripPrefix=1


  #admin 客户端配置
  boot:
    admin:
      client:
        url: http://localhost:8887
        username: rainbow
        password: 123456
        instance:
          prefer-ip: true
#配置了SBA客户端的名称，描述和版本信息；
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

# * 表示将SBA客户端的所有监控端点都暴露给SBA服务端；
management:
  endpoints:
    web:
      exposure:
        include: '*'
    #表示总是展示详细的健康信息。
  endpoint:
    health:
      show-details: ALWAYS